@local = http://localhost:3000

PUT {{local}}/api/products/update-product/61ae47bad6085f2370848a5f
Content-Type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MWE1NzhkY2I5NjA4MzYxNzhhMmMzN2YiLCJiaXoiOnRydWUsImlhdCI6MTYzODIzNDMzNn0.aGvDtKK3Qk_AvjoyAEn1-2WtLvC89vo0O56PsBiYkuE

{
  "imagePath": "https://i.insider.com/5d0150e06fc9200b5a05f042?width=1000&format=jpeg&auto=webp",
  "title": "test 2",
  "description": "This is my first product!!!",
  "price": 100
}