@local = http://localhost:3900

### Only users whom business can create a card {biz: true}
POST {{local}}/api/cards
Content-Type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MWQ2NTkyNDg2ODZiNThjYjFlMDZiNTAiLCJiaXoiOnRydWUsImlhdCI6MTY0MTY0ODQwM30.d3iFWfl1HCiUJhP4dhe9lOllQ6JhO4H0qY-U1Bs0xJA

{
  "bizName": "Guitar Lession",
  "bizDescription": "Guitar lession for beginners",
  "bizAddress": "Rishon lezion Herzrl.St",
  "bizPhone": "0524881862"
}