@local = http://localhost:3900

### User-Registration Aviran
POST {{local}}/api/users
Content-Type: application/json

{
  "name": "sadasd asdasdasd",
  "email": "asdsadsadasd@gmail.com",
  "password": "123456",
  "biz": true
}