export const actionTypes = {
  /**
   * CART
   */
  SET_ITEMS_TO_CART: "SET_ITEMS_TO_CART",
  ADD_TO_CART: "ADD_TO_CART",
  REMOVE_FROM_CART: "REMOVE_FROM_CART",
  INCREMENT_ITEM: "INCREMENT_ITEM",
  REDUCE_ITEM: "REDUCE_ITEM",
  CHECKOUT_USER_PAYMENT: "CHECKOUT_USER_PAYMENT",

  /**
   * PRODUCTS
   */
  SET_PRODUCTS: "SET_PRODUCTS",
  SET_BUSINESS_USER_PRODUCTS: "SET_BUSINESS_USER_PRODUCTS",
  GET_SELLER_DETAILS: "GET_SELLER_DETAILS",
  SELECTED_PRODUCT: "SELECTED_PRODUCT",
  CREATE_PRODUCT: "CREATE_PRODUCT",

  /**
 * CARDS
 */
  CREATE_CARD: "CREATE_CARD",
  EDIT_CARD: "EDIT_CARD",
  DISPLAY_USER_CARD: "DISPLAY_USER_CARD",
}




